In [2]:
import pandas as pd
from sqlalchemy import create_engine

# Define your connection details
server = 'ctrt-sqlserver.database.windows.net'
database = 'ctrt-sqldb'
username = 'CTRT-admin'
password = 'Hso2Ghana'
crime_Kumasi = 'silver.MG_Crimes_Kumasi'
crime_Accra = 'silver.MG_Crimes_Accra'
port = '1433'  # Default is 1433, e.g., '1433'

# Create the connection string for SQLAlchemy
connection_string = (
    f"mssql+pyodbc://{username}:{password}@{server}:{port}/{database}"
    "?driver=ODBC+Driver+17+for+SQL+Server"
)

# Establish the connection using SQLAlchemy create_engine
engine = create_engine(connection_string, echo=False)  # Set echo=True for debugging

# Define the query
query1 = f"SELECT * FROM {crime_Kumasi}"
query2 = f"SELECT * FROM {crime_Accra}"

# Execute the query and load the data into a DataFrame
Kumasi_crime_df = pd.read_sql(query1, engine)
Accra_crime_df = pd.read_sql(query2, engine)

In [4]:

Accra_crime_df.head(5)

,title,url,snippet,Date,Region
0,How gentrification is forcing Ghanaians out of...,https://www.opendemocracy.net/en/5050/ghana-ge...,Rampant development and soaring property price...,2023-11-27,Accra
1,"Court remands footballer, 3 others in police c...",https://3news.com/news/crime/court-remands-foo...,The Achimota District Court has remanded four ...,2024-06-03,Accra
2,"Sowutuom, Nima: Canadian government warns citi...",https://www.ghanaweb.com/GhanaHomePage/NewsArc...,The Government of Canada has updated its Trave...,2024-01-25,Accra
3,Police on manhunt for lone robber terrorising ...,https://www.adomonline.com/police-on-manhunt-f...,The Ghana Police Service (GPS) is on a manhunt...,2023-10-05,Accra
4,Ablekuma Bullion Van Robbery: How Police Arres...,https://www.peacefmonline.com/pages/local/crim...,One of the key suspects in the Ablekuma bullio...,2023-07-16,Accra

In [5]:
Kumasi_crime_df.head(5)

,title,url,snippet,Date,Region
0,Police urged to help address juvenile crime ar...,https://gna.org.gh/2023/10/police-urged-to-hel...,"By Dorothy Frances Ward. Kumasi, Oct 19, GNA –...",2023-10-19,Ashanti
1,Kumasi: Another househelp faces jail for murde...,https://www.asaaseradio.com/kumasi-another-hou...,The suspect made a second appearance before th...,2024-01-18,Ashanti
2,Jirapa Dubai CEO's murder case transferred to ...,https://www.adomonline.com/jirapa-dubai-ceos-m...,Residents of Jirapa in the Upper West Region h...,2024-06-03,Ashanti
3,Manso Nkran Gets Police Station,https://dailyguidenetwork.com/manso-nkran-gets...,REPORTED CASES of violent crimes and other ill...,2023-12-12,Ashanti
4,Domestic staff for Kumasi wey land court say e...,https://www.bbc.com/pidgin/articles/cp61dp1gl62o,Di domestic staff wey dey face accuse say e ki...,2023-09-19,Ashanti

In [6]:
Kumasi_crime_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 88 entries, 0 to 87
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   title    88 non-null     object
 1   url      88 non-null     object
 2   snippet  88 non-null     object
 3   Date     88 non-null     object
 4   Region   88 non-null     object
dtypes: object(5)
memory usage: 3.6+ KB

In [7]:
Accra_crime_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 79 entries, 0 to 78
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   title    79 non-null     object
 1   url      79 non-null     object
 2   snippet  79 non-null     object
 3   Date     79 non-null     object
 4   Region   79 non-null     object
dtypes: object(5)
memory usage: 3.2+ KB

In [8]:
crimes_df=pd.concat([Kumasi_crime_df,Accra_crime_df])
crimes_df

,title,url,snippet,Date,Region
0,Police urged to help address juvenile crime ar...,https://gna.org.gh/2023/10/police-urged-to-hel...,"By Dorothy Frances Ward. Kumasi, Oct 19, GNA –...",2023-10-19,Ashanti
1,Kumasi: Another househelp faces jail for murde...,https://www.asaaseradio.com/kumasi-another-hou...,The suspect made a second appearance before th...,2024-01-18,Ashanti
2,Jirapa Dubai CEO's murder case transferred to ...,https://www.adomonline.com/jirapa-dubai-ceos-m...,Residents of Jirapa in the Upper West Region h...,2024-06-03,Ashanti
3,Manso Nkran Gets Police Station,https://dailyguidenetwork.com/manso-nkran-gets...,REPORTED CASES of violent crimes and other ill...,2023-12-12,Ashanti
4,Domestic staff for Kumasi wey land court say e...,https://www.bbc.com/pidgin/articles/cp61dp1gl62o,Di domestic staff wey dey face accuse say e ki...,2023-09-19,Ashanti
...,...,...,...,...,...
74,Mass Promotion In Police Service,https://newsghana.com.gh/mass-promotion-in-pol...,Ghana Police Logo ONE HUNDRED-and forty-one po...,2012-03-14,Accra
75,Macbaron Hotel Manager Grabbed For Killing Clo...,https://newsghana.com.gh/macbaron-hotel-manage...,"DSP REYNOLDS Manteaw, Tema Community 1 Distric...",2012-12-11,Accra
76,10 Most Dangerous Cities in Ghana (2024 Updated),https://www.travelsafe-abroad.com/most-dangero...,Learn about some of the most dangerous cities ...,2023-10-10,Accra
77,10 Safest Cities in Ghana (2024 Updated),https://www.travelsafe-abroad.com/safest-citie...,Ghana is one of a few underappreciated tourist...,2023-10-10,Accra
78,"Uber & Bolt drivers, Tonaton & Jiji users blac...",https://www.mynewsgh.com/uber-bolt-drivers-ton...,"Teshie Nungua, a suburb of Accra has been blac...",2022-08-15,Accra